model:
  base_model: yolo11s.pt
  person_model: yolo11s.pt
  training:
    epochs: 50
    batch_size: 16
    image_size: 640
    patience: 10
  prediction:
    confidence_threshold: 0.3
    iou_threshold: 0.5
roboflow:
  workspace: nopaldetector
  project: nopal-detector-0lzvl
  version: 4
  format: yolov11
data:
  validation_split: 0.2
  random_seed: 42
output:
  predictions_dir: outputs/predictions
  videos_dir: outputs/videos
  weights_dir: models/weights
