# Configuración del Modelo
model:
  # Modelo base para entrenamiento de nopales
  base_model: "yolo11s.pt"

  # Modelo pre-entrenado para detección de personas
  person_model: "yolo11s.pt"

  # Configuración de entrenamiento
  training:
    epochs: 50
    batch_size: 16
    image_size: 640
    patience: 10

  # Configuración de predicción
  prediction:
    confidence_threshold: 0.3
    iou_threshold: 0.5

# Configuración de Roboflow
roboflow:
  # La API key se carga desde variable de entorno ROBOFLOW_API_KEY
  workspace: "nopaldetector"
  project: "nopal-detector-0lzvl"
  version: 2
  format: "yolov11"

# Configuración de datos
data:
  validation_split: 0.2
  random_seed: 42

# Configuración de salida
output:
  predictions_dir: "outputs/predictions"
  videos_dir: "outputs/videos"
  weights_dir: "models/weights"
